# Generated by Django 5.2.1 on 2025-07-11 14:35

import desafio.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0002_categoria_video_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='cor',
            field=models.CharField(default='#2EC27E', max_length=7, validators=[desafio.validators.is_valid_cor]),
        ),
    ]
